backend:
  name: github
  repo: jakeprins/serverless-saas
  branch: netlify-cms
media_folder: public/img
public_folder: img
collections:
  - name: 'pages'
    label: 'Pages'
    files:
      # Home page
      - label: 'Home'
        name: 'home'
        file: 'content/home.md'
        fields:
          # Hero section
          - { label: 'Hero Title', name: 'hero_title', widget: 'string' }
          - {
              label: 'Hero Description',
              name: 'hero_description',
              widget: 'markdown',
            }
          - {
              label: 'Hero Button Label',
              name: 'hero_button_label',
              widget: 'string',
            }
          # Features section
          - label: 'Features'
            name: 'features'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
          - label: 'Steps'
            name: 'steps'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
          # Pricing section
          - { label: 'Pricing Title', name: 'pricing_title', widget: 'string' }
          - {
              label: 'Pricing Description',
              name: 'pricing_description',
              widget: 'string',
            }
          - label: 'Plan'
            name: 'plan'
            widget: list
            fields:
              - { label: 'Name', name: 'name', widget: 'string' }
              - { label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Price', name: 'price', widget: 'string' }
              - label: 'USP'
                name: 'usp'
                widget: list
                fields:
                  - { label: 'Name', name: 'name', widget: 'string' }
          # Team section
          - { label: Team Title, name: team_title, widget: string }
          - {
              label: Team Description,
              name: team_description,
              widget: markdown,
            }
          - label: Team
            name: team
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Position, name: position, widget: string }
              - { label: Photo, name: photo, widget: image }

  # Blog posts
  - name: 'posts'
    label: 'Posts'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    preview_path: 'posts/{{fields.slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Slug', name: 'slug', widget: 'string' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', default: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Category', name: 'category', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
